import { Campaign, ColumnConfig, AgencyProfile } from './types';

export const INITIAL_AGENCY_PROFILE: AgencyProfile = {
  name: 'Rahmatullah Agency',
  adminName: 'Rahmatullah Sakib',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
};

// STRICT REQUIREMENT: Default Column Order
// 1) Status
// 2) Spent
// 3) Client
// 4) Budget
// 5) Duration
// 6) Direction
// 7) Category
// 8) Ad Account
// 9) Submitter & Marketer
export const DEFAULT_COLUMNS: ColumnConfig[] = [
  { id: 'status', label: 'Status', widthPercent: 9 },
  { id: 'spent', label: 'Spent', widthPercent: 11 },
  { id: 'client', label: 'Client', widthPercent: 15 },
  { id: 'budget', label: 'Budget', widthPercent: 12 },
  { id: 'duration', label: 'Duration', widthPercent: 12 },
  { id: 'direction', label: 'Direction', widthPercent: 13 },
  { id: 'category', label: 'Category', widthPercent: 10 },
  { id: 'adAccount', label: 'Ad Account', widthPercent: 9 },
  { id: 'team', label: 'Submitter & Marketer', widthPercent: 9 },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: '7492',
    clientName: 'NovaTech Solutions',
    campaignName: 'Brand Awareness',
    status: 'Active',
    spent: 820.40,
    dailyBudget: 50.00,
    totalBudget: 1500.00,
    startDate: '2026-04-25',
    endDate: '2026-05-25',
    direction: 'Tech founders, 25-45, Tier 1 cities only',
    category: 'E-commerce',
    adAccount: 'Meta Ads',
    submittedBy: 'Rahmatullah Sakib',
    marketer: 'Tanjila Akter',
    magicToken: 'magic_7492_nv92',
    quickNotes: 'High priority client. Scale ad spend by 15% on weekends if ROAS > 3.2.',
  },
  {
    id: '3819',
    clientName: 'GreenMart',
    campaignName: 'Product Launch',
    status: 'Active',
    spent: 1320.75,
    dailyBudget: 80.00,
    totalBudget: 2400.00,
    startDate: '2026-04-22',
    endDate: '2026-05-22',
    direction: 'Eco-conscious shoppers, Women 20-40',
    category: 'E-commerce',
    adAccount: 'Instagram Ads',
    submittedBy: 'Nusrat Jahan',
    marketer: 'Rahmatullah Sakib',
    magicToken: 'magic_3819_gm38',
    quickNotes: 'Client sensitive to creative tone; only use approved organic green palette.',
  },
  {
    id: '5124',
    clientName: 'FitLife Gym',
    campaignName: 'Lead Generation',
    status: 'Paused',
    spent: 540.20,
    dailyBudget: 40.00,
    totalBudget: 1200.00,
    startDate: '2026-04-20',
    endDate: '2026-05-20',
    direction: 'Within 8km radius, Ages 18-35 gym goers',
    category: 'Others',
    adAccount: 'Google Ads',
    submittedBy: 'Tanjila Akter',
    marketer: 'Rafiul Islam',
    magicToken: 'magic_5124_fl51',
  },
  {
    id: '9201',
    clientName: 'StyleHub',
    campaignName: 'Website Traffic',
    status: 'Active',
    spent: 1260.60,
    dailyBudget: 70.00,
    totalBudget: 2100.00,
    startDate: '2026-04-18',
    endDate: '2026-05-18',
    direction: 'Women fashion, 18-30, Mobile Instagram feed',
    category: 'E-commerce',
    adAccount: 'Meta Ads',
    submittedBy: 'Rahmatullah Sakib',
    marketer: 'Nusrat Jahan',
    magicToken: 'magic_9201_sh92',
  },
  {
    id: '4832',
    clientName: 'FreshBite',
    campaignName: 'Video Views',
    status: 'Active',
    spent: 720.30,
    dailyBudget: 45.00,
    totalBudget: 1350.00,
    startDate: '2026-04-16',
    endDate: '2026-05-16',
    direction: 'Foodies, University campuses, Evening 6-10 PM',
    category: 'Others',
    adAccount: 'TikTok Ads',
    submittedBy: 'Rafiul Islam',
    marketer: 'Tanjila Akter',
    magicToken: 'magic_4832_fb48',
  },
  {
    id: '6190',
    clientName: 'Apex Cars',
    campaignName: 'Traffic Conversion',
    status: 'Rejected',
    spent: 0.00,
    dailyBudget: 100.00,
    totalBudget: 3000.00,
    startDate: '2026-04-14',
    endDate: '2026-05-14',
    direction: 'Men 30-55, High income brackets only',
    category: 'Others',
    adAccount: 'Google Ads',
    submittedBy: 'Nusrat Jahan',
    marketer: 'Rahmatullah Sakib',
    magicToken: 'magic_6190_ac61',
  },
  {
    id: '8342',
    clientName: 'GlowBeauty',
    campaignName: 'Brand Awareness',
    status: 'Active',
    spent: 1020.45,
    dailyBudget: 60.00,
    totalBudget: 1800.00,
    startDate: '2026-04-12',
    endDate: '2026-05-12',
    direction: 'Skincare enthusiasts, Women only',
    category: 'E-commerce',
    adAccount: 'Instagram Ads',
    submittedBy: 'Tanjila Akter',
    marketer: 'Rafiul Islam',
    magicToken: 'magic_8342_gb83',
  },
  {
    id: '2941',
    clientName: 'EduPlus',
    campaignName: 'Student Admission Lead',
    status: 'Active',
    spent: 480.75,
    dailyBudget: 30.00,
    totalBudget: 900.00,
    startDate: '2026-04-10',
    endDate: '2026-05-10',
    direction: 'IELTS / Higher study applicants, 18-26',
    category: 'Student Consultancy',
    adAccount: 'Meta Ads',
    submittedBy: 'Rahmatullah Sakib',
    marketer: 'Nusrat Jahan',
    magicToken: 'magic_2941_ep29',
  },
  {
    id: '7753',
    clientName: 'TravelVista',
    campaignName: 'Holiday Packages',
    status: 'Active',
    spent: 1620.30,
    dailyBudget: 75.00,
    totalBudget: 2250.00,
    startDate: '2026-04-08',
    endDate: '2026-05-08',
    direction: 'Frequent flyers, Bangkok & Dubai seekers',
    category: 'Travel',
    adAccount: 'Google Ads',
    submittedBy: 'Rafiul Islam',
    marketer: 'Tanjila Akter',
    magicToken: 'magic_7753_tv77',
  },
  {
    id: '1589',
    clientName: 'HomeDecor',
    campaignName: 'Product Launch',
    status: 'Paused',
    spent: 760.20,
    dailyBudget: 55.00,
    totalBudget: 1650.00,
    startDate: '2026-04-06',
    endDate: '2026-05-06',
    direction: 'New homeowners, 28-50, Living room focus',
    category: 'E-commerce',
    adAccount: 'Instagram Ads',
    submittedBy: 'Nusrat Jahan',
    marketer: 'Rahmatullah Sakib',
    magicToken: 'magic_1589_hd15',
  },
  {
    id: '6420',
    clientName: 'TechGear',
    campaignName: 'Video Showcase',
    status: 'Active',
    spent: 1980.65,
    dailyBudget: 90.00,
    totalBudget: 2700.00,
    startDate: '2026-04-04',
    endDate: '2026-05-04',
    direction: 'Gamers, PC enthusiasts, 16-35',
    category: 'E-commerce',
    adAccount: 'YouTube Ads',
    submittedBy: 'Tanjila Akter',
    marketer: 'Rafiul Islam',
    magicToken: 'magic_6420_tg64',
  },
  {
    id: '9034',
    clientName: 'WellnessCo',
    campaignName: 'Recruitment Drive',
    status: 'Completed',
    spent: 1950.00,
    dailyBudget: 65.00,
    totalBudget: 1950.00,
    startDate: '2026-04-02',
    endDate: '2026-05-02',
    direction: 'Skilled healthcare staff, Gulf region ready',
    category: 'Manpower',
    adAccount: 'Meta Ads',
    submittedBy: 'Rahmatullah Sakib',
    marketer: 'Nusrat Jahan',
    magicToken: 'magic_9034_wc90',
  },
];
